### GET all users

GET  http://localhost:3000/api/users HTTP/1.1


### GET a single user
GET http://localhost:3000/api/users/Zied HTTP/1.1


### GET a single user which doesn't exist

GET http://localhost:3000/api/users/Elias HTTP/1.1

### Delete a user

DELETE  http://localhost:3000/api/users/David HTTP/1.1